call py .\rechercheParameters.py 1_rienAFaire
call py .\rechercheParameters.py 2_simpleBoucle
call py .\rechercheParameters.py 3_simpleBoucleAvecDebut
call py .\rechercheParameters.py 4_simpleBoucleAvecFin
call py .\rechercheParameters.py 5_simpleBoucleAvecDebutEtFin
call py .\rechercheParameters.py 6.01_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.02_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.03_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.04_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.05_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.06_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.07_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.08_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.09_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.10_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.11_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.12_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.13_simpleBoucleAvecIf
call py .\rechercheParameters.py 6.14_simpleBoucleAvecIf
call py .\rechercheParameters.py 7.01_bouclesEnSequence
call py .\rechercheParameters.py 7.02_bouclesEnSequence
call py .\rechercheParameters.py 8_bouclesEnSequenceAvecIf
call py .\rechercheParameters.py 9.01_bouclesImbriquees
call py .\rechercheParameters.py 9.02_bouclesImbriquees
call py .\rechercheParameters.py 9_bouclesImbriquees
