/*
    This file is part of Prog&Play: A library to enable interaction between a
    strategy game and program of a player.
    Copyright 2009 Mathieu Muratet

    Prog&Play is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Prog&Play is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Mathieu Muratet
    mathieu.muratet@lip6.fr
*/

#ifndef PP_ERROR_H
#define PP_ERROR_H

/**
 * \file PP_Error.h
 * \brief Interface to manage errors.
 * \author Muratet.M
 * \date March 5, 2013
 *
 * Provides an interface to manage errors generated by Prog&Play API.
 *
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \brief Provides last error generated by Prog&Play API.
 *
 * \return the last error set as a string ended by NULL. This string is
 * statically allocated and hasn't to be freed by the user.
 */
char * PP_GetError(void);

/**
 * \brief Cleans the last error.
 *
 * Deletes all informations from the last internal error. Useful if error has
 * been processed.
 */
void PP_ClearError(void);

#ifdef __cplusplus
};
#endif

#endif /* PP_ERROR_H */
